name: CA Hometraders
favicon: null
layout_spectrum: 0.75539
typography_spectrum: 0.73969
title: CA Hometraders
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d72826'
    - '#191919'
    - '#6c696b'
    - '#db8487'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
